--- 
title: "Mekanik Kuantum"
author: "Murthadza Aznam"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_book: default
  pdf_document: default
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: thaza-Kun/mekanik-kuantum
url: https://thaza-kun.github.io/mekanik-kuantum/
description: Catatan ilmiah teknikal Mekanik Kuantum
site: bookdown::bookdown_site
---

# Prakata {-}

> "Pengajaran daripada kisah ini ialah kita tidak patut cuba mencapai banyak perkara sekaligus. Kita seharusnya mengasingkan satu masalah fizik daripada masalah fizik yang lain sejauh mungkin. Kemudian, barulah kita boleh singkirkannya satu demi satu."
>
>`r tufte::quote_footer('--- Paul Dirac (1989)')`

Bagi memulakan buku ini, eloklah kita menghayati petikan fizikawan ulung Paul Dirac daripada rencananya, '[Kaedah Kerja dalam Fizik Teori](https://fizikkini.com/kaedah-kerja-dalam-fizik-teori-bahagian-i/)'. Kisah yang dirujuk oleh beliau itu sebenarnya ialah kisah pencarian persamaan Schr&ouml;dinger. Ia menepati tema utama kebanyakan kursus pengenalan mekanik kuantum: iaitu agar pelajar memahami dan memahiri persamaan Schr&ouml;dinger.

Lagipun, petikan itu adalah satu nasihat umum yang baik: jangan terlalu ghairah cuba menyelesaikan semua perkara sekaligus tetapi kenal pasti masalah-masalah kecil di laluan kejayaan tersebut dan selesaikanlah ia sedikit demi sedikit. Jika kita ditimpa satu masalah yang besar, ingatlah akan kata ini lalu pecahkannya menjadi masalah-masalah yang kecil dan cuba singkirkannya sedikit demi sedikit.

Usaha membina masyarakat berilmu ialah satu cabaran yang besar dan memakan masa. Langkah pertama yang perlu diambil ialah belajar menyampaikan ilmu dalam bahasa masyarakat tersebut serta menyediakan acuan agar ia boleh berkembang. Usaha saya menyediakan bahan bacaan hanyalah satu langkah kecil untuk mencapai cita-cita tersebut setelah memahiri laras ilmiah bahasa Melayu.

Semoga ia bermanfaat.

## Dorongan Projek {-}

Laman sesawang [MajalahSains](www.majalahsains.com) yang diasaskan oleh Mohd Faizal Aziz boleh dilihat sebagai mercu tanda usaha pemasyarakatan sains di samudera maya bernama internet. Di sebalik bangun jatuh banyak portal sains yang lain, MajalahSains tetap megah mengibarkan benderanya pada ribuan pembaca yang melawatnya. Jelaslah orang ramai masih minat mengikuti berita sains.

Kewujudan MajalahSains juga memberi peluang kepada portal-portal sains lain untuk turut berkembang sama. Misalnya [Apadilangit](https://apadilangit.com/) yang diasaskan oleh Muhammad Hafez Ahmat Murtza pada tahun 2016 melaksanakan pelbagai program di luar dan dalam talian. Apadilangit inilah yang menjadi wakil Malaysia untuk memberi nama bintang dan eksoplanet melalui kutipan cadangan dari pelajar-pelajar sempena sambutan 100 tahun Kesatuan Astronomi Antarabangsa, IAU.^[Nama yang diberikan oleh Malaysia ialah 'Intan' untuk bintangnya dan 'Baiduri' untuk eksoplanetnya (@iau2019).]

Saluran [Ajar](https://www.youtube.com/c/AjarMalaysia) (walaupun bukan menumpu pada sains semata-mata) yang diasaskan oleh Muhammad Haziq Abdul Rahim pula telah meraih sehingga 270 ribu pelanggan di YouTube melangkaui Anugerah Butang Main Perak walaupun baru berumur 3 tahun! Itu adalah pencapaian yang sangat mengagumkan!

Pemasyarakatan sains, atau umumnya pemasyarakatan ilmu, sedang galak dilaksanakan oleh bicarawan-bicarawan sains yang sudah ataupun yang belum mendapat nama. Kegiatan menyampaikan sains dalam konteks popular ini seringkali menyabitkan nama Carl Sagan sebagai pengasas dan amalannya meluas sehingga muncul banyak saluran YouTube berkaitannya. Di Malaysia, ia masih di peringkat tunas.

Kemunculan golongan seperti MajalahSains, Apadilangit, dan Ajar, telah menyediakan momentum yang cukup agar tanah maya terus disuburkan dengan bahan-bahan ilmiah popular. Saya yakin, dalam sedekad dua kelak, akan muncul nama-nama baharu yang akan menyambung kerja mereka.

Sudah tiba masanya untuk kita agihkan tenaga untuk menyuburkan kandungan sains teknikal pula. Hakikatnya, usaha melahirkan peminat sains dibina atas keinginan melahirkan pakar dalam bidang ini. Maka, penghasilan bahan ilmiah popular dan bahan ilmiah teknikal perlukan keseimbangan.

Penulisan bahan rujukan teknikal sains berbahasa Melayu bukanlah sesuatu yang baharu. Antaranya ialah "Pengenalan Mekanik Kuantum" (1996) dan "Fizik Moden" (1989) oleh Prof Mohammad Yahaya; "Superkonduktor: Konvensional dan Suhu Tinggi" (1996) oleh Prof Roslan Abdul Shukor; serta "Vektor dan Tensor: Suatu Pendekatan Terkamir" (1991) dan "Tensor dan Bentuk Pembeza" (2000) oleh Prof Shaharir Mohd Zain. Prof Shaharir ada banyak lagi hasil tulisan dalam bidang Sains, Matematik dan Falsafah Sains yang tidak mampu saya senaraikan.

Entah berapa ramai lagi penulis ilmiah serta bukunya yang tidak kita ketahui. Ada eloknya jika kita geledah perpustakaan ilmiah kita untuk mengorek khazanah-khazanah ilmu ini.

Adapun semua ini, buku-buku tersebut hanya wujud di alam nyata. Dunia internet ialah satu pustaka yang luas; maka amatlah rugi jika pustaka maya ini kelompongan bahan rujukan. Jumlah bahan ilmiah dalam pustaka nyata dan pustaka maya perlukan keseimbangan.

Buat masa ini, kelihatannya seperti tiada bahan rujukan ilmiah sains berbahasa Melayu yang dijumpai di internet, terutamanya untuk pengajian tinggi. Oleh itu, projek Catatan Fizik Teori ini bertujuan untuk memulakan langkah pertama mengisi kelompongan itu.

Karya ini adalah hasil teladan daripada wargamaya seluruh dunia. Ada banyak jenis rujukan yang mereka hasilkan dan sebahagiannya (mungkin sebenarnya sebahagian besar daripadanya) bukanlah daripada kuliah atau kursus bersilibus tetapi hanya sekadar catatan mereka berkaitan ilmu yang diteroka itu.

Lagipun, amalan mengongsikan catatan kuliah sudah lama diamalkan oleh para mahasiswa tetapi selalunya ia adalah perkongsian dari senior ke junior kursus tersebut. Maka, projek ini adalah perkembangan wajar daripada amalan tersebut.

## Tentang Penulis {-}

Murthadza bin Aznam ialah seorang pelajar Sarjana Muda Fizik Gunaan di Universiti Kebangsaan Malaysia sejak sesi 2017/2018 dan dijangka akan habis pada sesi 2021/2022. Beliau berkecimpung dalam dunia penulisan sains popular sejak 2016 melalui pelbagai saluran. Selain itu, beliau pernah menyunting di MajalahSains untuk tempoh yang singkat pada tahun 2018 dan pernah menterjemah beberapa penulisan sains.

## Tentang Buku {-}

Buku ini, *Catatan Fizik Teori: Mekanik Kuantum*, merupakan catatan penulis sepanjang belajar Mekanik Kuantum di Universiti Kebangsaan Malaysia. Sebahagian besarnya merupakan catatan daripada kuliah Mekanik Kuantum. Namun begitu, ada bahagian yang ditokok tambah daripada pembacaan peribadi penulis yang dirasakan perlu diulas.

Buku ini dihasilkan menggunakan [Bookdown](https://bookdown.org/home/) yang disediakan oleh @xie2015. Ia menggunakan Markdown yang dicampur kefungsian LaTeX. Markdown ialah sejenis alat penulisan yang membantu penulis menumpukan perhatian pada isinya dan bukan rupanya. Rupa bentuk buku akan ditentukan oleh pemprosesnya. Dalam kes ini pemprosesnya ialah Bookdown dan bentuk yang kalian baca inilah hasilnya.

LaTeX pula ialah alat untuk menulis formula dengan mudah dan cantik. Alat ini dikira sebagai piawai antarabangsa untuk menulis formula matematik. Misalnya, wikipedia menulis persamaan-persamaannya menggunakan tatatanda LaTeX. Markdown yang mentah tiada sokongan LaTeX tetapi Bookdown ada sokongan penulisan LaTeX yang memadai. Jadi, sebab itulah saya gunakannya untuk menulis buku ini yang sarat Matematik.