# Persamaan Schrödinger

::::::{.callout-note appearance="minimal"}
##
:::::{#thm-schroedinger} 
## Persamaan Schrödinger
::::{.panel-tabset}

## 1 Dimensi
Pertimbangkan suatu zarah berfungsi gelombang $\Psi(x, t)$ yang merambat dalam medan keupayaan $V(x, t)$, maka sifat zarah tersebut tertakluk pada persamaan berikut:
$$
    \frac{-\hbar^2}{2m}\frac{\partial^2}{\partial x^2}\Psi(x, t) + V(x, t)\Psi(x, t) = i\hbar\frac{\partial}{\partial t}\Psi(x, t)
$$

:::{.callout-note collapse="true"} 
## dengan maksud bahawa...
| simbol | maksud | nilai |
| :---: | :--- | :--- |
| $\hbar$ | pemalar Planck palang | $1.054571817...\times 10^{−34}$ J$\cdot$s |
| $m$ | jisim zarah | pembolehubah tidak bersandar |
| $x$ | kedudukan | pembolehubah tidak bersandar |
| $t$ | masa | pembolehubah tidak bersandar |
| $V(x, t)$ | keupayaan | fungsi bersandar $x$ dan $t$ |
| $\Psi(x, t)$ | fungsi gerlombang | fungsi bersandar $x$ dan $t$ |
:::

## 3 Dimensi
Pertimbangkan suatu zarah berfungsi gelombang $\Psi(r, t)$ yang merambat dalam medan keupayaan $V(r, t)$, maka sifat zarah tersebut tertakluk pada persamaan berikut:
$$
    \frac{-\hbar^2}{2m}\nabla^2\Psi(r, t) + V(r, t)\Psi(r, t) = i\hbar\frac{\partial}{\partial t}\Psi(r, t)
$$

:::{.callout-note collapse="true"}
## dengan maksud bahawa...
| simbol | maksud | nilai |
| :---: | :--- | :--- |
| $\hbar$ | pemalar Planck palang | $1.054571817...\times 10^{−34}$ J$\cdot$s |
| $m$ | jisim zarah | pembolehubah tidak bersandar |
| $r$ | kedudukan dalam 3 dimensi | pembolehubah tidak bersandar |
| $t$ | masa | pembolehubah tidak bersandar |
| $V(r, t)$ | keupayaan | fungsi bersandar $r$ dan $t$ |
| $\Psi(r, t)$ | fungsi gelombang | fungsi bersandar $r$ dan $t$ |
| $\nabla^2$ | operator Laplace | $\frac{\partial^2}{\partial x^2} + \frac{\partial^2}{\partial y^2} + \frac{\partial^2}{\partial z^2}$ |
:::
::::
:::::
::::::